# Generated by Django 3.1 on 2021-03-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rating_ratingstar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
