# Generated by Django 3.1 on 2021-03-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210315_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='movie',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='movie',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='movie',
            new_name='post',
        ),
    ]
